name: InspectRLIs
description: Updates all outdated RLIs in the Sphinx project.
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  root:
    description: 'Root Directory of Sphinx project'
    required: true
    default: '$GITHUB_WORKSPACE'
  latestVersion:
    description: 'Version of RLIs to enforce. If not specified here, will be taken from the JSON file pointed to by INSPECTOR_CONFIG.'
    required: false
  baseUrl:
    description: 'Base URL of all RLIs. If not specified here, will be taken from the JSON file pointed to by INSPECTOR_CONFIG.'
    required: false
  versionScheme:
    description: 'A regex that all RLI versions match. If not specified here, will be taken from the JSON file pointed to by INSPECTOR_CONFIG.'
    required: false
outputs:
  report:
    description: 'Full Report; written to the `report.md` file, console, and this output.'
  report-file-path:
    description: 'Full path to the `report.md` file.'
  needs-manual:
    description: '`true` if there are RLIs that need manual updating, `false` otherwise.'
  up-to-date:
    description: '`true` if everything is up-to-date, `false` otherwise.'