name: InspectRLIs
description: Updates all outdated RLIs in the Sphinx project.
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  root:
    description: 'Root Directory of Sphinx project'
    required: true
    default: '$GITHUB_WORKSPACE'
  latestVersion:
    description: 'Version of RLIs to enforce'
    required: true
  baseUrl:
    description: 'Base URL of all RLIs'
    required: true
  versionScheme:
    description: 'A regex that all RLI versions match'
    required: true
outputs:
  report:
    description: 'Full Report; written to the `report.md` file, console, and this output.'
  report-file-path:
    description: 'Full path to the `report.md` file.'
  needs-manual:
    description: '`true` if there are RLIs that need manual updating, `false` otherwise.'