name: Inspector
description: Updates all outdated RLIs in the Sphinx project.
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  root:
    description: 'Root Directory of Sphinx project'
    required: true
    default: '$GITHUB_WORKSPACE'
  baseUrl:
    description: 'Base URL of RLIs'
    required: true
  ignoredFiles:
    description: 'Files to ignore'
    required: false
    default: '[]'
  latestVersion:
    description: 'Version to update RLIs to'
    required: true
  versionScheme:
    description: 'A regex of the version strings'
    required: true
outputs:
  report:
    description: 'Full Report; written to the `report.md` file, console, and this output.'
  report-file-path:
    description: 'Full path to the `report.md` file.'
  needs-manual:
    description: '`true` if there are RLIs that need manual updating, `false` otherwise.'
  up-to-date:
    description: '`true` if everything is up-to-date, `false` otherwise.'
